name: 'Fix Undetected Vulnerabilities'
description: 'Set the status of any vulnerabilities not detected at all in the latest version to FIXED.'
author: 'Scott Tolley'
inputs:
  seekerServerURL: 
    description: 'Seeker Server URL - will fall back to the environment variable SEEKER_SERVER_URL if not set.'
  seekerProjectKey: 
    description: 'Seeker Project Key - will fall back to the environment variable SEEKER_PROJECT_KEY if not set.'
  seekerAPIToken:
    description: 'Seeker API Token - you should store your Seeker API Token securely as an ecrypted secret.'
  seekerProjectVersion:
    description: 'Seeker Project Version - will fall back to the environment SEEKER_PROJECT_VERSION is not set.'
  closeFixedIssues:
    description: 'Close linked issues in GitHub automatically.'

runs:
  using: 'node12'
  main: '../lib/fix-undetected-vulnerabilities.js'