# Seeker Compliance Reporting
# ###########################
#
# This action packages up check-seeker-compliance to determine whether or not the Seeker project is
# in compliance after running all the tests, and seeker-compliance-report - optionally, if
# generateComplianceReportPDF is set to true - to generate a PDF compliance report artefact.

name: 'Seeker Compliance Reporting'
description: 'Check Seeker Compliance policies. Optionally: download the Seeker Compliance Report and/or fail the build action.'
author: 'Scott Tolley'
inputs:
  seekerServerURL: 
    description: 'Seeker Server URL - will fall back to the environment variable SEEKER_SERVER_URL if not set.'
  seekerProjectKey: 
    description: 'Seeker Project Key - will fall back to the environment variable SEEKER_PROJECT_KEY if not set.'
  seekerAPIToken:
    description: 'Seeker API Token - will fall back to the environment variable SEEKER_API_TOKEN if not set.'
  generateComplianceReportPDF:
    description: 'The Seeker Compliance Report will be generated and added as a build artefact.'
    default: false
  failBuildIfNotInCompliance:
    description: 'Fail the build action if the Seeker Compliance Policy check fails.'
    default: false

# It would be great to implement this by just calling the two actions: check-seeker-compliance
# and seeker-compliance report. Sadly it is not possible to do this today, so we have to call
# the JavaScript action seeker-compliance-reporting that does the same thing.
runs:
  using: 'node12'
  main: '../lib/seeker-compliance-report.js'